#!/usr/bin/python3

import jlog
import argparse

def main():
    
    # parse arguments 
    parser = argparse.ArgumentParser(description="Write some logs!")
    parser.add_argument("--now", dest="timestamp_level", help="Timestamp to now")
    args = parser.parse_args()
    jl = jlog.JLog(jlog.Timestamp_level.NOW, jlog.Log_type.LOG)
    jl.write_to_log("Message sample")

main()
