#!/usr/bin/python3

import jlog
import argparse

def main():
    
    # parse arguments 
    parser = argparse.ArgumentParser(description="Write some logs!")
    parser.add_argument("-m", dest="message", help="write quick message")
    args = parser.parse_args()
    jl = jlog.JLog(jlog.Timestamp_level.NOW, jlog.Log_type.LOG)

    if args.message:
        jl.write_to_log(args.message)

main()
